# Generated by Django 4.0.7 on 2022-10-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miningtaxes", "0003_characterminingledgerentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterminingledgerentry",
            name="raw_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="characterminingledgerentry",
            name="refined_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="characterminingledgerentry",
            name="taxed_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="characterminingledgerentry",
            name="taxes_owed",
            field=models.FloatField(default=0.0),
        ),
    ]
